<?php

return [
    'survey' => [
        'code' => 'GEOBOSQUES_PRESSURE',
        'name' => 'Encuesta de Presión sobre el Bosque',
        'type' => 'PRE',
        'description' => 'Instrumento GeoBosques para registrar factores de presión y el estado de conservación del bosque.',
        'requires_coordinates' => true,
    ],
    'viewer' => [
        'provider' => env('GEOBOSQUES_PROVIDER', 'GEOBOSQUES_MINAM'),
        'base_url' => env('GEOBOSQUES_VIEWER_URL', 'https://geobosques.minam.gob.pe/geobosque/visor/index.php'),
        'marker_parameter' => env('GEOBOSQUES_MARKER_PARAMETER', 'xy'),
    ],
    'questions' => [
        [
            'order' => 1,
            'eje' => 'Ubicación',
            'question_text' => 'Ubicación',
            'question_type' => 'UBICACION',
            'type_field' => 'UBICACION',
            'calculator_value_type' => 'location',
            'calculator_unit' => null,
            'is_required' => true,
            'justification' => 'Departamento, provincia y distrito.',
            'options' => [],
        ],
        [
            'order' => 2,
            'eje' => 'Ubicación',
            'question_text' => 'Comunidad / Centro poblado',
            'question_type' => 'LIBRE',
            'type_field' => 'CORTO',
            'calculator_value_type' => 'string',
            'calculator_unit' => null,
            'is_required' => true,
            'justification' => '-',
            'options' => [],
        ],
        [
            'order' => 3,
            'eje' => 'Accesibilidad',
            'question_text' => '¿Cuál es la distancia desde el bosque hasta el acceso más cercano? (carretera, trocha o camino, río navegable, otro acceso)',
            'question_type' => 'LIBRE',
            'type_field' => 'NUMERICO',
            'calculator_value_type' => 'number',
            'calculator_unit' => 'km',
            'is_required' => true,
            'justification' => 'Unidad: km.',
            'options' => [],
        ],
        [
            'order' => 4,
            'eje' => 'Actividad agrícola',
            'question_text' => '¿Cuál de las opciones describe mejor la agricultura en el bosque?',
            'question_type' => 'OPCIONES',
            'type_field' => 'LISTADO',
            'calculator_value_type' => 'options',
            'calculator_unit' => null,
            'is_required' => true,
            'justification' => '-',
            'options' => [
                'Los cultivos se encuentran a más de 2km del bosque y no tienen mucha expansión.',
                'Los cultivos se encuentran a menos de 2km del bosque y su expansión es limitada.',
                'Los cultivos están dentro o muy cerca al bosque y se observa una expansión.',
            ],
        ],
        [
            'order' => 5,
            'eje' => 'Asentamientos humanos',
            'question_text' => '¿Cuál es la distancia entre el bosque hasta su centro poblado/comunidad?',
            'question_type' => 'LIBRE',
            'type_field' => 'NUMERICO',
            'calculator_value_type' => 'number',
            'calculator_unit' => 'km',
            'is_required' => true,
            'justification' => 'Unidad: km.',
            'options' => [],
        ],
        [
            'order' => 6,
            'eje' => 'Aprovechamiento forestal',
            'question_text' => 'En una semana habitual ¿cuántos días usted o algun integrante de su hogar extrae productos del bosque para el uso particular de su familia, como leña, madera, frutos o plantas?',
            'question_type' => 'OPCIONES',
            'type_field' => 'LISTADO',
            'calculator_value_type' => 'options',
            'calculator_unit' => null,
            'is_required' => true,
            'justification' => '-',
            'options' => [
                '1 - 2 días por semana',
                '3 - 4 días por semana',
                '5 - 7 días por semana',
            ],
        ],
        [
            'order' => 7,
            'eje' => 'Perturbación del bosque',
            'question_text' => '¿Cuál de las siguientes opciones describe mejor el bosque?',
            'question_type' => 'OPCIONES',
            'type_field' => 'LISTADO',
            'calculator_value_type' => 'options',
            'calculator_unit' => null,
            'is_required' => true,
            'justification' => '-',
            'options' => [
                'El bosque se encuentra en buen estado de conservación.',
                'Se observan algunos focos de deforestación, incendios o degradación por alguna otra actividad.',
                'Se observan grandes focos de deforestación, incendios recurrentes o degradación por otra actividad.',
            ],
        ],
    ],
];
